- name: create new vhost
  hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  become: yes
  become_user: root
  vars_files:
    - config/{{ vhost }}.yml
  
  tasks:
    - name: import vhost config debugging task
      include_tasks: tasks/debug-vhost-config.yml
      when: debug_config is defined and debug_config
    
    - name: start primary tasks
      block:
        -
          debug:
            msg: nothing
      when: not debug_config is defined or not debug_config