- name: create new vhost
  hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  become: true
  become_user: root
  vars_files:
    - config/{{ vhost }}.yml

  tasks:
    - name: import vhost config debugging task
      block:
        - include_tasks: tasks/dump-vhost-config.yml
        - meta: end_play
      when:
        - dump_conf is defined and dump_conf

      # this should be for installing and configuring things like:
      # - php, node, and other runtimes
      # - web server
      # - database engine
      # - any ssl cert generator if necessary
      # - supporting packages
      #
      # stuff that can be installed together like apt packages should be
      # grouped (hopefully)
      #
      # asdf or others that need to be installed one-by-one can be grouped
      # or handled one-by-one within task files (probably)
    - name: ensure prerequisites are set up
      block:
        - debug:
            msg: nothing yet

    - name: configure db
      block:
        - stat:
            path: tasks/configure-{{ db.type }}-db.yml
          register: db_task

        - debug:
            msg: config for db type {{ db.type }} not found
          when: not db_task.stat.exists

        - include_tasks: "{{ db_task.stat.path }}"
          when: db_task.stat.exists

    - name: configure php runtime
      block:
        - include_tasks: tasks/configure-php-fpm.yml

    - name: configure vhost
      block:
        - include_tasks: tasks/link-project.yml

        - stat:
            path: tasks/configure-{{ server }}-site.yml
          register: srv_task

        - debug:
            msg: task file not found for server type {{ server }}
          when: not srv_task.stat.exists

        - name: shove hostname into hosts file
          lineinfile:
            state: present
            dest: /etc/hosts
            line: |
              127.0.0.1 {{ project.hostname }} www.{{ project.hostname }}
          when: srv_task.stat.exists

        - include_tasks: "{{ srv_task.stat.path }}"
          when: srv_task.stat.exists
