- name: configure nginx site
  block:
    - name: store nginx site conf path
      set_fact:
        site_conf_path: /etc/nginx/sites-available/{{ project.hostname }}

    - name: register sites-available conf path
      stat:
        path: "{{ site_conf_path }}"
      register: site_conf

    - name: print message if site conf already exists
      debug:
        msg: site conf for {{ project.hostname }} exists
      when: site_conf.stat.exists

    - name: create site conf
      template:
        src: templates/nginx-site.j2
        dest: "{{ site_conf_path }}"
        mode: 0644
      when: not site_conf.stat.exists

    - name: store site conf link path
      set_fact:
        site_link_path: /etc/nginx/sites-enabled/{{ project.hostname }}

    - name: register sites-enabled conf path
      stat:
        path: "{{ site_link_path }}"
      register: site_link

    - name: print message if site conf already linked
      debug:
        msg: link for site conf {{ project.hostname }} exists
      when: site_link.stat.exists

    - name: final nginx setup
      block:
        - name: link site conf
          file:
            state: link
            src: "{{ site_conf.stat.path }}"
            dest: "{{ site_link_path }}"
        - name: restart nginx
          ansible.builtin.systemd:
            name: nginx
            state: restarted
      when:
        - site_conf.stat.exists
        - not site_link.stat.exists
