- name: configure project mysql db
  block:
    - name: ensure mysql is running
      ansible.builtin.systemd:
        state: started
        name: mysqld

    - name: create mysql database if it's missing
      community.mysql.mysql_db:
        name: "{{ db.name }}"
        encoding: "{{ db.encoding }}"
        collation: "{{ db.collation }}"
        login_unix_socket: "{{ db.socket }}"
        login_user: "{{ db.login_user }}"
        login_password: "{{ db.login_pw }}"
        state: present

    - name: create the db user and grant privileges if it's missing
      community.mysql.mysql_user:
        name: "{{ db.user }}"
        password: "{{ db.password }}"
        priv: "{{ db.name }}.*:ALL"
        login_unix_socket: "{{ db.socket }}"
        login_user: "{{ db.login_user }}"
        login_password: "{{ db.login_pw }}"
        state: present
