- name: configure php {{ php.version }} fpm
  block:
    - name: check php fpm directory
      stat:
        path: /etc/php/{{ php.version }}/fpm
      register: fpm_dir

    - name: print when root fpm dir not found
      debug:
        msg: php {{ php.version }} fpm directory not found
      when: not fpm_dir.stat.exists

    - name: store vhost fpm conf path
      set_fact:
        vhost_fpm_conf_path: "{{ fpm_dir.stat.path }}/pool.d/{{ vhost }}.conf"

    - name: check php fpm vhost conf
      stat:
        path: "{{ vhost_fpm_conf_path }}"
      register: vhost_fpm_conf

    - name: final php fpm setup
      block:
        - name: write php fpm vhost conf
          template:
            src: templates/php-fpm-site.conf.j2
            dest: "{{ vhost_fpm_conf_path }}"
            mode: 0644
        - name: restart php fpm
          ansible.builtin.systemd:
            name: php8.4-fpm
            state: reloaded
      when:
        - fpm_dir.stat.isdir is defined
        - fpm_dir.stat.isdir
        - not vhost_fpm_conf.stat.exists
