- name: print vars task group
  block:
    - name: print vars from provided config file
      debug:
        msg:
          - "Hostname: {{ project.hostname }}"
          - "Project directory: {{ project.dir }}"
          - "PHP version: {{ php.version }}"
          - "FPM settings:"
          - "User: {{ php.fpm.user }}"
          - "Group: {{ php.fpm.group }}"
          - "Listening user: {{ php.fpm.listen.user }}"
          - "Listening group: {{ php.fpm.listen.group }}"
          - "Database:"
          - "Type: {{ db.type }}"
          - "Host: {{ db.host }}"
          - "Name: {{ db.name }}"
          - "User: {{ db.user }}"
          - "Server: {{ server }}"
