- name: print vars task group
  block:
    - name: print vars from provided config file
      debug:
        msg:
          - "Hostname: {{ hostname }}"
          - "Project directory: {{ project_dir }}"
          - "PHP version: {{ php }}"
          - "FPM settings:"
          - "User: {{ fpm.user }}"
          - "Group: {{ fpm.group }}"
          - "Listening user: {{ fpm.listen.user }}"
          - "Listening group: {{ fpm.listen.group }}"
          - "Database:"
          - "Type: {{ db.type }}"
          - "Host: {{ db.host }}"
          - "Name: {{ db.name }}"
          - "User: {{ db.user }}"
          - "Server: {{ server }}"